export enum LAYER_TYPES {
    LAYER_VECTOR = 'VECTOR',
    LAYER_RASTER = 'RASTER',
    LAYER_UNKNOWN = 'UNKNOWN'
}

export enum AFFILIATION_TYPES {
    AFFILIATION_INPUT = 'INPUT',
    AFFILIATION_OUTPUT = 'OUTPUT',
    AFFILIATION_UNKNOWN = 'UNKNOWN'
}


